### ISSUE TITLE
HELP TO COMPILE

### ISSUE THREAD

**Issue by Dazmed707** [javiarago1/SplinterRAT#2]
I install pre-requisites for windows 11, how to compile server and client? I have install VISUAL STUDIO 2022

**Comment by javiarago1** [comment]
Hi! 
Today I will upload an unstable release (executable JAR) so you can test it out . Anyway you can compile the jcServer using IntelliJ.

Best regards

**Comment by Dazmed707** [comment]
Ok, thanks.
U write a guide instalation o a video with IntelliJ ? I not program in Java, also C# and Python.

**Comment by javiarago1** [comment]
https://www.youtube.com/watch?v=uSfRkOWsQRo&ab_channel=K4GCybeX

This is a good video for it, but i recommend you to wait a few days cause i'm finishing perfecting some details and it might not work in the current version.

**Comment by javiarago1** [comment]
Release is out, you can download it now!
