### ISSUE TITLE
Error complie cliente

### ISSUE THREAD

**Issue by Dazmed707** [javiarago1/SplinterRAT#3]
I INSTALL MSYS2 AND COMAND pacman -S mingw-w64-x86_64-toolchain

![image](https://user-images.githubusercontent.com/35184132/207395476-b0a973af-3d45-43fc-bae4-14fbba18240b.png)

![image](https://user-images.githubusercontent.com/35184132/207395619-29a583a6-7cf2-42a6-a8b9-423cd332de4a.png)

**Comment by javiarago1** [comment]
Hello

It should work now, problems with paths was the problem, new release has been updated

Best regards

**Comment by Dazmed707** [comment]
Release Alpha2?

**Comment by Dazmed707** [comment]
No found Compile Button and folder to .exe compile program?

**Comment by javiarago1** [comment]
The repository (source) versión doesn't contains the zip file of the cliente, only the release .exe or .jar

**Comment by Dazmed707** [comment]
I AM COMPILING, BUT I CAN'T FIND THE .EXE

ALSO, THE COMPILE BUTTON OF THE PROGRAM DOES NOT WORK FOR THE CLIENT.

**Comment by Dazmed707** [comment]
I using source code

Realease Binary not found Compile Button for client.

**Comment by javiarago1** [comment]
Updated release, should work now!
