### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by uzaypardo** [javiarago1/SplinterRAT#4]
![image](https://user-images.githubusercontent.com/35384154/208062654-7e1edaab-d4b9-4f50-8a90-b43aa0e80d32.png)

**Comment by javiarago1** [comment]
Have you installed msys2 with mingw64? Send picture with your current g++ --version in cmd.

**Comment by uzaypardo** [comment]
$ g++ --version
g++.exe (Rev4, Built by MSYS2 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by javiarago1** [comment]
What OS are u using?

**Comment by javiarago1** [comment]
Updated release files, it should work now! 

Best regards

**Comment by uzaypardo** [comment]
![image](https://user-images.githubusercontent.com/35384154/208297643-b37dca5d-2f76-4bd4-b30f-60ab0b4e16e9.png)
 windows 10 , i downloaded new version but the some problem.

**Comment by javiarago1** [comment]
Sen

**Comment by uzaypardo** [comment]
> Send me picture of modules selected

![image](https://user-images.githubusercontent.com/35384154/208297973-be880620-7b67-4a44-92be-7a35fac693fc.png)

**Comment by javiarago1** [comment]
![Captura de pantalla 2022-12-18 132102](https://user-images.githubusercontent.com/76445432/208298101-78a29608-6d19-46f1-99db-e1ddc4be3d62.png)

Delete this folder and try again

**Comment by uzaypardo** [comment]
This time it does not give an error, but it does not create the exe either.

**Comment by javiarago1** [comment]
Send me picture of every configuration on compiler (Installatio, identification, etc) and tell me if it does compile now

**Comment by uzaypardo** [comment]
![image](https://user-images.githubusercontent.com/35384154/208314907-7b6aadd3-8753-4f1f-b2b3-f9510e3305ef.png)
![image](https://user-images.githubusercontent.com/35384154/208315155-336ef60b-9777-4b52-b557-0a40138841b4.png)
![image](https://user-images.githubusercontent.com/35384154/208315299-d6a81ad5-f743-4cf7-bccb-01cd45e5df00.png)

**Comment by javiarago1** [comment]
Picture of splinterrat configuration inside Builder. I want to see the identificación, installation, etc

**Comment by uzaypardo** [comment]
![image](https://user-images.githubusercontent.com/35384154/208317504-9f31102e-6496-4a6d-9ff2-c92194261bca.png)
![image](https://user-images.githubusercontent.com/35384154/208317541-72332a03-e454-457b-b312-67bad4bffbc9.png)
![image](https://user-images.githubusercontent.com/35384154/208317555-6fdefa92-9fc2-4f08-a665-b604963c17e6.png)
![image](https://user-images.githubusercontent.com/35384154/208317577-7564b1e4-d497-43bc-af10-5aaa62d90492.png)
![image](https://user-images.githubusercontent.com/35384154/208317589-8ab88af5-7e10-419f-9216-35fb3ca0aeb4.png)

**Comment by javiarago1** [comment]
Delete splinterrat fólder in appdata. Then in install mode inside Builder -> installation set to appdata, there is some kind of problem in system installation maybe.

**Comment by uzaypardo** [comment]
![image](https://user-images.githubusercontent.com/35384154/208371517-acd0478f-bde4-4465-af5f-af5f57fba91a.png)
![image](https://user-images.githubusercontent.com/35384154/208371628-a2ab6f0b-73fc-4d5c-898c-1fef7f4c36ac.png)
![image](https://user-images.githubusercontent.com/35384154/208371702-fee17351-60d3-4d5e-8e9b-4bca0c9ab38e.png)
![image](https://user-images.githubusercontent.com/35384154/208371830-d9397fc9-99ac-41bc-a743-ff0727e9d2b9.png)

**Comment by uzaypardo** [comment]
this time it does not give an error, but it does not create the exe either.

**Comment by uzaypardo** [comment]
![image](https://user-images.githubusercontent.com/35384154/208607685-b523570b-d6e5-4eb1-9297-cc184ff7cad4.png)

**Comment by javiarago1** [comment]
Set default system compiler and add mingw64/bin to path variables

**Comment by javiarago1** [comment]
Found the error! Steps to fix it:

- Delete SplinterRAT folder /AppData/
- Download last release

**Comment by uzaypardo** [comment]
![image](https://user-images.githubusercontent.com/35384154/208843478-60f204b1-c247-462d-b759-b4565024845b.png)

**Comment by uzaypardo** [comment]
i sent it
