### ISSUE TITLE
Ability to resize screen viewer / Webcam/Screen monitoring

### ISSUE THREAD

**Issue by izShelby** [javiarago1/SplinterRAT#6]
The live screen viewer is rather small, a way to make it larger would be nice.

Highjacking my own issue... 

Webcam/Screen monitoring checkbox doesn't seem to do anything, at least the WLogs directory was never created for my test bench.

Props for the work!

**Comment by izShelby** [comment]
I basically just checked the webcam/screen monitoring checkbox in the settings while building the client and left the folder name at default (WLogs). I also checked the keylog checkbox with default folder name settings (KLogs).
When I went to check for the files, I found the KLogs folder, but I couldn't find the WLogs one. So I'm assuming it wasn't created. I tried running the cam a couple times to see if that would make the client create it, but nothing happened.
Am I doing something wrong here?

**Comment by javiarago1** [comment]
No, you are not doing anything wrong, the folder is only created when you record the webcam and is deleted when you download the recordings, to avoid accumulation of videos (it would be a very heavy folder)

**Comment by izShelby** [comment]
Okay, I assumed that it would be used for passive monitoring. That clears things up then.

**Comment by javiarago1** [comment]
fixed!
